import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import './globals.css'
import Providers from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lightning Asset Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Sidebar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
